version: build_{build}
image: Visual Studio 2017
clone_folder: C:\gafferDependencies
environment:
  BUILD_DIR: C:\gafferDependenciesBuild
  CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
  BUILD_TYPE: RELEASE
  BOOST_MSVC_VERSION: msvc-14.0
  ROOT_DIR: C:\gafferDependencies

  VERSION: 0.48.0.0
platform: x64

init:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script: 
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - C:\gafferDependencies\winbuild\buildAll.bat
artifacts:
  - path: C:\gafferDependencies\gafferDependencies-%VERSION%-windows-msvc2017.zip