version: build_{build}
image: Visual Studio 2017
clone_folder: C:\gafferDependencies
environment:
  BUILD_DIR: C:\gafferDependenciesBuild
  VERSION: 0.48.0.0
platform: x64
build_script: 
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - C:\gafferDependencies\winbuild\buildAll.bat
artifacts:
  - path: C:\gafferDependencies\gafferDependencies-%VERSION%-windows-msvc2017.zip