version: {build}
image: Visual Studio 2017
clone_folder: C:\gafferDependencies
environment:
  BUILD_DIR: C:\gafferDependenciesBuild
  VERSION: 0.48.0.0
platform: x64
build_script: 
  - C:\gafferDependencies\winbuild\buildAll.bat
artifacts:
  - path: C:\gafferDependencies\gafferDependencies-$(VERSION)-windows-msvc2017.zip